# Generated by Django 5.2.3 on 2025-06-17 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispositivocadastrado',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HistoricoDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('vazao', models.FloatField()),
                ('volume_acumulado', models.FloatField()),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='api.dispositivocadastrado')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
