# Generated by Django 5.2.3 on 2025-06-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_address_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursohidrico',
            name='tipo',
            field=models.CharField(choices=[('RESERVATORIO', 'Reservatório'), ('POCO', 'Poço'), ('DESSALINIZADOR', 'Dessalinizador'), ('REDE_DISTRIBUICAO', 'Rede de distribuição')], default='RESERVATORIO', max_length=50),
        ),
    ]
